### ISSUE TITLE
xaml namespaces are not preserved when using defered loader

### ISSUE THREAD

**Issue by donandren** [cwensley/Portable.Xaml#47]
example:

DataTemplate is defered loader. Static extension is not able to resolve the type local:NonControl
as namespaces context is not preserved in the defered loader:
```
<ContentControl xmlns='https://github.com/avaloniaui'
            xmlns:local='clr-namespace:Avalonia.Markup.Xaml.UnitTests.Xaml;assembly=Avalonia.Markup.Xaml.UnitTests'>
    <ContentControl.ContentTemplate>
        <DataTemplate>
            <TextBlock  Tag='{Static local:NonControl.StringProperty}'/>
        </DataTemplate>
    </ContentControl.ContentTemplate>
</ContentControl>
```

Example unit test:
https://github.com/donandren/Avalonia/blob/portablexaml/tests/Avalonia.Markup.Xaml.UnitTests/Xaml/BasicTests.cs#L820-L840

Currently I've found work around writing namespaces to the defered content:
https://github.com/donandren/Avalonia/blob/portablexaml/src/Markup/Avalonia.Markup.Xaml/Templates/TemplateContent.cs#L16-L25

**Comment by cwensley** [comment]
This looks like it is by design.  System.Xaml from .NET 4.5 doesn't appear to preserve namespaces in the resulting node list either.  You can determine this by running the tests in the `Portable.Xaml-tests-net_4_5` on windows.

Since you have a way to make it work for your purposes, I think that would be sufficient and we don't need to extend Portable.Xaml to provide extra functionality here.  Thoughts?

**Comment by donandren** [comment]
that's fine, we have a way to overcome this issue with bit more advanced loader and manually attaching namespaces

**Comment by cwensley** [comment]
Excellent, thanks for the feedback.  I might snag your unit test you added if that's alright just to make sure that works going forward.
