### ISSUE TITLE
Do not write unnecessary type information in generated xaml

### ISSUE THREAD

**Issue by wieslawsoltes** [cwensley/Portable.Xaml#61]
Xaml writer adds unnecessary type information in generated xaml

This is generated xaml:
https://gist.github.com/wieslawsoltes/48644ca196fc740f85cc8ce1019042b3#file-and_fixed-xaml-L3

and this is with removed type information:
https://gist.github.com/wieslawsoltes/d36baf6bb4a858d125438f04c61301ed#file-and_fixed_immutable-xaml-L3

Both version deserialize without errors.

**Comment by yariker** [comment]
It should be noted that these two ways of initializing collection properties in XAML are not completely equivalent. When collection type is omitted, a deserializer (XamlObjectWriter) first tries to get an existing collection instance by reading the property value, and then it calls the IList.Add method on it to fill the items. Thus, such a collection property doesn't even need to have a public setter.

The second way is more explicit, but it does a slightly different thing. It first creates a collection of exactly the specified type (ImmutableArray<XPoint> in your case), and then sets the property value. Thus, such a property needs to have a public setter.

Of course if you take an immutable collection, the second way is only option, so that's what XAML writer generates.

Interestingly enough, if you remove a public setter, and try to deserialize a XAML with an implicit collection initialization (without a type), it wouldn't even throw an error, and the collection will remain empty (is it a bug?). So I guess XAML writer tries to be safe here, and chooses an explicit way.

**Comment by cm4ker** [comment]
@cwensley What do you think? Does we need to change behavour of this? It seems what it is not a bug and it (as I understand) different with System.Xaml.

**Comment by cwensley** [comment]
@cm4ker if this can be done without breaking certain scenarios, then sure.

I don't think it's a requirement if System.Xaml doesn't provide this functionality, but it would just be an enhancement (opt-in via a setting property most likely) to Portable.Xaml that would make it nicer to use in this case.

**Comment by cm4ker** [comment]
@cwensley ok, I will think how to implement this.
